---
#
#
- hosts: testgroup
  user: centOS
  become: yes
  vars:
    TEMP_LOCATION: /tmp/openmpi
    FINAL_LOCATION: /opt/openmpi-1.10.2
    DEBUG_LOCATION: /tmp/openMPI-examples
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant
    mpi_tutorial_zip: 'https://github.com/mpitutorial/mpitutorial.git'
    mpi_tutorial_repo_dest: "{{ DEBUG_LOCATION }}/mpitutorial-master"
  name: OpenMPI Deployment beginning ...
  tasks:
  - name: Install openmpi
    yum: name={{ item }} state=present
    with_items:
      - openmpi
    tags:
      - easy

  - name: Install git
    yum: name={{ item }} state=present
    with_items:
      - git
    tags:
      - easy

  

  - name: Extract MPI Tutorial project
    git:
        repo: 'https://github.com/mpitutorial/mpitutorial.git'
        dest: "{{ DEBUG_LOCATION }}"
    tags:
      - easy

  - name: Compiling Hello world
    shell: mpicc {{ DEBUG_LOCATION }}/tutorials/mpi-hello-world/code/mpi_hello_world.c
    tags:
      - easy

  