---
#
#
- hosts: testgroup
  user: ubuntu
  become: yes
  vars:
    TEMP_LOCATION: /tmp/openmpi
    FINAL_LOCATION: /opt/openmpi-1.10.2
    DEBUG_LOCATION: /tmp/openMPI-examples
    ansible_ssh_user: vagrant
    ansible_ssh_pass: vagrant
    mpi_tutorial_zip: 'https://github.com/mpitutorial/mpitutorial.git'
    mpi_tutorial_repo_dest: "{{ DEBUG_LOCATION }}/mpitutorial-master"
    johntheripper_repo: 'https://github.com/magnumripper/JohnTheRipper.git'
    johntheripper_dest: /home/vagrant/JohnTheRipper
  name: OpenMPI Deployment beginning ...
  tasks:

  - name: Update ubuntu ...
    apt: update_cache=yes
    tags:
      - easy

  - name: Clone repository
  git:
    repo: "{{ johntheripper_repo }}"
    dest: "{{ johntheripper_dest }}"
    version: "{{ johntheripper_version }}"
    update: no
  register: gitclone

 